let clubs = [
    {
        id: 1,
        subject: "Music",
        location: "School A",
        fee: 20,
        image: "images/music.jpg",
        rating: 3,
        availableInventory: 5,
    },
    {
        id: 2,
        subject: "Journalism",
        location: "School B",
        fee: 25,
        image: "images/journalism.jpg",
        rating: 4,
        availableInventory: 3,
    },
    {
        id: 3,
        subject: "Cricket",
        location: "Park A",
        fee: 15,
        image: "images/cricket.jpeg",
        rating: 5,
        availableInventory: 10,
    },
    {
        id: 4,
        subject: "Football",
        location: "Park B",
        fee: 30,
        image: "images/football.jpg",
        rating: 4,
        availableInventory: 4,
    },
    {
        id: 5,
        subject: "Swimming",
        location: "Pool A",
        fee: 35,
        image: "images/swimming.jpg",
        rating: 4,
        availableInventory: 7,
    },
    {
        id: 6,
        subject: "Art",
        location: "School C",
        fee: 40,
        image: "images/art.jpg",
        rating: 3,
        availableInventory: 6,
    },
    {
        id: 7,
        subject: "Robotics",
        location: "Tech Lab",
        fee: 50,
        image: "images/robotics.webp",
        rating: 4,
        availableInventory: 5,
    },
    {
        id: 8,
        subject: "Debate",
        location: "School D",
        fee: 10,
        image: "images/debate.jpg",
        rating: 4,
        availableInventory: 8,
    },
    {
        id: 9,
        subject: "Cooking",
        location: "Kitchen A",
        fee: 45,
        image: "images/cooking.jpeg",
        rating: 4,
        availableInventory: 3,
    },
    {
        id: 10,
        subject: "Dance",
        location: "Dance Studio",
        fee: 25,
        image: "images/dance.jpg",
        rating: 5,
        availableInventory: 10,
    }
];
